clemenger_comment_homepage:
    path:     /{parentId}
    defaults: { _controller: ClemengerCommentBundle:Default:index, parentId: null }

comment_show:
    path:     /comment/{commentId}
    defaults: { _controller: ClemengerCommentBundle:Default:showComment }