clemenger_comment_homepage:
    path:     /
    defaults: { _controller: ClemengerCommentBundle:Default:index }

comment_show:
    path:     /comment/{commentId}
    defaults: { _controller: ClemengerCommentBundle:Default:showComment }